// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205094907_UpdateOneToOne")]
    partial class UpdateOneToOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConcertId"));

                    b.Property<string>("ConcertName")
                        .HasColumnType("text");

                    b.Property<int>("ConcertSpecId")
                        .HasColumnType("integer");

                    b.HasKey("ConcertId");

                    b.HasIndex("ConcertSpecId")
                        .IsUnique();

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("WebApplication1.Models.ConcertSpec", b =>
                {
                    b.Property<int>("ConcertSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConcertSpecId"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConcertSpecId");

                    b.ToTable("ConcertSpecs");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Concert", b =>
                {
                    b.HasOne("WebApplication1.Models.ConcertSpec", "ConcertSpecs")
                        .WithOne("concert")
                        .HasForeignKey("WebApplication1.Models.Concert", "ConcertSpecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConcertSpecs");
                });

            modelBuilder.Entity("WebApplication1.Models.ConcertSpec", b =>
                {
                    b.Navigation("concert")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
