// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209094957_update1.3")]
    partial class update13
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConcertId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("ConcertId"), 100L, null, null, null, null, null);

                    b.Property<string>("ConcertName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConcertId");

                    b.ToTable("Concerts");
                });

            modelBuilder.Entity("WebApplication1.Models.ConcertSpec", b =>
                {
                    b.Property<int>("ConcertSpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConcertSpecId"));

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Date_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.HasKey("ConcertSpecId");

                    b.HasIndex("ConcertId")
                        .IsUnique();

                    b.ToTable("ConcertSpecs");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.ConcertSpec", b =>
                {
                    b.HasOne("WebApplication1.Models.Concert", "Concert")
                        .WithOne("ConcertSpecs")
                        .HasForeignKey("WebApplication1.Models.ConcertSpec", "ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("WebApplication1.Models.Concert", b =>
                {
                    b.Navigation("ConcertSpecs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
